### ISSUE TITLE
[BUG] - Teams Get (With parameter) method returns an error

### ISSUE THREAD

**Issue by lathindu1** [onfleet/php-onfleet#7]
Hello guys, I tried to integrate OnFleet with my client's requirements. My main requirement is to get the team from the team id using your API. This team id is received from **workerCreated** webhook.

01 I tried to list all the teams using **$onfleet->teams->get()**. This works without any issue.
<img width="422" alt="Screenshot 2022-05-28 at 07 23 47" src="https://user-images.githubusercontent.com/16050349/170805239-811ed099-aafb-4152-9c04-60010265c034.png">

02 I tried to get single team by parsing team id to function **$onfleet->teams->get('team id')** . but it redirect me to an error.

<img width="1495" alt="Screenshot 2022-05-28 at 07 11 07" src="https://user-images.githubusercontent.com/16050349/170805248-ce562fff-0319-4bf4-b649-c520dcf16680.png">

<img width="808" alt="Screenshot 2022-05-28 at 07 10 51" src="https://user-images.githubusercontent.com/16050349/170805256-ed380d7e-2430-4850-939c-ab7753285787.png">

So, then I tried to debug the error. As I saw, Inside **methods.php line no 81** , it's trying to get the 2nd key (key=1) from the args array while it only has a single key (key=0).

<img width="1740" alt="Screenshot 2022-05-28 at 07 31 34" src="https://user-images.githubusercontent.com/16050349/170805610-4af321d1-5929-40af-b537-878e90de278e.png">

to **avoid** this we can put a simple **array_key_exists** to line no **81**

**array_key_exists(1, $args)**

Hope you guys may fix this asap.

**Comment by vic-onfleet** [comment]
@lathindu1 Thank you for filling this bug. I have reported it to our engineer, we will release a fix soon.

**Comment by vic-onfleet** [comment]
Hi @lathindu1,

Our developer cannot reproduce the issue. Can you please share the code that is giving you this error, not the stack trace? And the team ID? You can share the team ID in a private note sent to victoria@onfleet.com and the code too if you like.

**Comment by ali-issa** [comment]
Hi @vic-onfleet, we're getting the same error with ` $onfleet->tasks->deleteOne()`. Replacing `in_array($args[1]` with `in_array($args[0]` as @lathindu1 mentioned solves the problem.

**Comment by ali-issa** [comment]
Hi @vic-onfleet, we're getting the same error when using `$onfleet->tasks->deleteOne()`. Is there a plan to fix the bug anytime soon?

**Comment by iamrasec** [comment]
Hi @vic-onfleet , we too are getting the same error for $onfleet->teams->get('team id') and on $onfleet->tasks->get(['from' => <timestamp>]).  Hope this bug gets fixed soon.  The fix @lathindu1 suggested looks promising.
